### ISSUE TITLE
Importing from 'inferno/core/VNodes' can't be resolved

### ISSUE THREAD

**Issue by IgnusG** [rendall/inferno-jsx-type-definitions#1]
### Background
I was trying to use this type definition and ended up putting it in my typings folder as a new file. Typescript now picks up the definitions but I'm getting an error from inside of it.

### Error
```
import { Ref as VNodeRef } from 'inferno/core/VNodes'
```
cannot be resolved. I fixed it by changing it to `inferno/src/core/VNodes` but this might be hinting at a problem with my setup.

Is this an issue or is the way I'm using the definition wrong?

**Comment by IgnusG** [comment]
I tried this in a different project and it worked flawlessly so the problem must have been somewhere else. Therefore closing

**Comment by rendall** [comment]
Hey IgnusG!  Sorry for not getting back to you before now.  I hadn't seen this.  I have to improve my notifications, I think.

Anyway, I'm glad it's worked out, but please feel free to reopen if there's a problem.
