### ISSUE TITLE
modify some points

### ISSUE THREAD

**Issue by PedroGao** [rendall/inferno-jsx-type-definitions#3]
the definitions is awesome! but when i add it to my project,the type check always report error!
so i change some points in the file!

1. delete the ReadOnly<>
2. change the state from S to S | null 

and it worked !

>  class Component<P, S> {
        constructor(props?: P, context?: any);

        // Disabling unified-signatures to have separate overloads. It's easier to understand this way.
        // tslint:disable:unified-signatures
        setState<K extends keyof S>(f: (prevState: S, props: P) => Pick<S, K>, callback?: () => any): void;
        setState<K extends keyof S>(state: Pick<S, K>, callback?: () => any): void;
        // tslint:enable:unified-signatures

        forceUpdate(callBack?: () => any): void;
        render(props:any): JSX.Element | null | false;

        // InfernoJSX.Props<T> is now deprecated, which means that the `children`
        // property is not available on `P` by default, even though you can
        // always pass children as variadic arguments to `createElement`.
        // In the future, if we can define its call signature conditionally
        // on the existence of `children` in `P`, then we should remove this.
        props: { children?: InfernoJSXNode } & P;
        // state: S; // attention 
        state: S | null;
        context: any;
        // refs: {
        //     [key: string]: InfernoJSXInstance
        // };
    }

**Comment by rendall** [comment]
Great! Nice feedback.  I will take a look later today.  Thanks.
